# Generated by Django 5.0 on 2024-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
