# Generated by Django 5.0 on 2023-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "ClientUser"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "CustomUser"},
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_client",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_lawyer",
            field=models.BooleanField(default=False),
        ),
    ]
