# Generated by Django 5.0 on 2024-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyerprofile_bio_lawyerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
