# Generated by Django 5.0 on 2024-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_verifytoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profiles/default-user.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
