# Generated by Django 5.0 on 2024-01-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="lawyer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.lawyer"
            ),
        ),
    ]
