# Generated by Django 5.0 on 2024-01-29 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_lawyerprofile_lawyer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="email",
            new_name="email_address",
        ),
    ]
