# Generated by Django 5.0 on 2024-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_rename_email_address_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
