# Generated by Django 5.0 on 2024-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinvetation',
            name='org_approvment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseinvetation',
            name='user_approvment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
