# Generated by Django 5.0 on 2024-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizatiostuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_number', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(choices=[('USD', 'United States dollar'), ('EUR', 'the Euro'), ('EGP', 'Egyptian pound')], max_length=10)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
