# Generated by Django 5.0 on 2024-01-24 11:33

import django.core.validators
import django.db.models.deletion
import subscribes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "nums_of_stuff",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ]
                    ),
                ),
                (
                    "start_deuration",
                    models.DateField(default=subscribes.models.get_current_date),
                ),
                ("end_deuration", models.DateField()),
                ("is_free", models.BooleanField(default=False)),
                ("price", models.FloatField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "United States dollar"),
                            ("EUR", "the Euro"),
                            ("EGP", "Egyptian pound"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("subscribe_Type", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscribeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=255)),
                ("companyAddres", models.TextField()),
                ("companyNo", models.CharField(blank=True, default="", max_length=200)),
                ("companyID", models.FileField(upload_to="companyID/")),
                ("companyURL", models.URLField(blank=True, null=True)),
                (
                    "companyEmail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("responsibleName", models.CharField(max_length=255)),
                ("responsiblePhone", models.CharField(max_length=15)),
                (
                    "responsibleEmail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "requestStatus",
                    models.CharField(
                        choices=[
                            ("underProcess", "تحت الاجراء"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("canceled", "ملغي"),
                            ("other", "اخرى"),
                        ],
                        default="تحت الاجراء",
                        max_length=30,
                    ),
                ),
                ("statusDiscription", models.TextField(blank=True, null=True)),
                (
                    "companyuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscribe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscribes.subscribe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscribeContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_discription", models.TextField(blank=True, null=True)),
                (
                    "subscribe_contract_status",
                    models.CharField(
                        choices=[
                            ("underProcess", "جاري التعاقد"),
                            ("paied", "مدفوع"),
                            ("unpaied", "غير مدفوع"),
                            ("canceled", "ملغي"),
                            ("rejected", "مرفوض"),
                            ("other", "اخرى"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nums_of_users", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("paied_amount", models.FloatField()),
                ("reciept_file", models.FileField(upload_to="recieptFile/")),
                ("contract_file", models.FileField(upload_to="contractDiscription/")),
                ("contract_discription", models.TextField(blank=True, null=True)),
                ("contract_aproval", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "subscribe_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscribes.subscribeorder",
                    ),
                ),
            ],
        ),
    ]
