# Generated by Django 5.0 on 2024-03-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='object_id',
        ),
    ]
