# Generated by Django 5.0 on 2024-01-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribes", "0001_initial"),
        ("users", "0003_lawyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeorder",
            name="companyuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lawyer",
            ),
        ),
    ]
