# Generated by Django 5.0 on 2024-02-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0002_alter_subscribeorder_companyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribecontract',
            name='nums_of_users',
        ),
        migrations.RemoveField(
            model_name='subscribecontract',
            name='reciept_file',
        ),
        migrations.AlterField(
            model_name='subscribecontract',
            name='subscribe_contract_status',
            field=models.CharField(choices=[('underProcess', 'جاري التعاقد'), ('paied', 'مدفوع'), ('unpaied', 'غير مدفوع'), ('canceled', 'ملغي'), ('rejected', 'مرفوض'), ('other', 'اخرى')], default='underProcess', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribeorder',
            name='requestStatus',
            field=models.CharField(choices=[('underProcess', 'تحت الاجراء'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('canceled', 'ملغي'), ('other', 'اخرى')], default='underProcess', max_length=30),
        ),
        migrations.CreateModel(
            name='SubscribeContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums_of_users', models.IntegerField()),
                ('reciept_file', models.FileField(upload_to='recipet_files/')),
                ('subscribe_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscribes.subscribecontract')),
            ],
        ),
    ]
