# Generated by Django 5.0 on 2024-02-04 07:07

import django.db.models.deletion
import subscribes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribes", "0003_remove_subscribecontract_nums_of_users_and_more"),
        ("users", "0011_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribecontract",
            name="nums_of_users",
            field=models.IntegerField(
                null=True, blank=True
            ),
        ),
        migrations.AddField(
            model_name="subscribecontract",
            name="reciept_file",
            field=models.FileField(blank=True, null=True, upload_to="recipet_files/"),
        ),
        migrations.AlterField(
            model_name="subscribecontract",
            name="contract_file",
            field=models.FileField(
                blank=True, null=True, upload_to="contractDiscription/"
            ),
        ),
        migrations.AlterField(
            model_name="subscribecontract",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscribecontract",
            name="paied_amount",
            field=models.FloatField(
                null=True, blank=True
            ),
        ),
        migrations.AlterField(
            model_name="subscribecontract",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscribeorder",
            name="companyuser",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lawyer",
            ),
        ),
        migrations.DeleteModel(
            name="SubscribeContractDetails",
        ),
    ]
